name: test

on:
  push:
    branches:
      - test

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Run Tests
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install Xvfb
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xvfb && sudo apt-get install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release xdg-utils wget ca-certificates
      - name: Install Packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Run Linux Test
        if: runner.os == 'Linux'
        run: xvfb-run -a npm test
      - name: Run Test
        if: runner.os != 'Linux'
        run: npm test